package myLangModel;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import static org.junit.Assert.assertEquals;

/**
 * This JUnit Test Class has been generated by right clicking on the MiscUtils class
 * and selecting "New" then "Junit Test Case". After that, you have to select the methods
 * for which you would like to generate tests.
 * In practice, you will duplicate manually the test methods to possibly create
 * several tests for one method.
 *
 * Your work is then to remove the fail parts and to implement each test.
 * One method is given as an example
 *
 * To run them:
 * either right click on the class name or simply on the method name and
 * select "Run As Junit Test".
 *
 * Class NgramUtilsTest: JUnit Test class to test the class NgramUtils.
 *
 * @author N. Hernandez and S. Quiniou (2015)
 *
 */
public class MyNgramUtilsTest {

    String sentence = "<s> cette phrase est de taille 9 . </s>";
    String ngram = "où commence l' historique de ce n-gramme";


	/*@Before
	public void initialize () {
		System.out.printf("Set ngram>%s<\n",ngram);
		System.out.printf("Set sentence>%s<\n",sentence);
	}*/


    /**
     * Test method for {@link NgramUtils#getSequenceSize(java.lang.String)}.
     */
    @Test
    public void testGetSequenceSize() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#generateNgrams(java.lang.String, int, int)}.
     */
    @Test
    public void testGenerateNgramsBigrams() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#generateNgrams(java.lang.String, int, int)}.
     */
    @Test
    public void testGenerateNgrams1to3grams() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#getHistory(java.lang.String, int)}.
     */
    @Test
    public void testGetHistoryOrder2() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#getHistory(java.lang.String, int)}.
     */
    @Test
    public void testGetHistoryOrder3() {
        // TODO

    }

    /**
     * Test method for {@link NgramUtils#getHistory(java.lang.String, int)}.
     */
    @Test
    public void testGetHistoryOrder0() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#decomposeIntoNgrams(java.lang.String, int)}.
     */
    @Test
    public void testDecomposeInto1grams() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#decomposeIntoNgrams(java.lang.String, int)}.
     */
    @Test
    public void testDecomposeInto2grams() {
        // TODO

    }


    /**
     * Test method for {@link NgramUtils#decomposeIntoNgrams(java.lang.String, int)}.
     */
    @Test
    public void testDecomposeInto3grams() {
        // TODO

    }


    /**
     *
     */
    @Test
    public void testWord2characterTokens() {
        // TODO
    }



    @Rule
    public TestName name = new TestName();

    @Before
    public void printSeparator()
    {
        System.out.println("\n=== " + name.getMethodName() + " =====================");
    }
}
